// <auto-generated />
using System;
using DAL.Modeles;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250424092046_UpdateSpectacleTitreSize")]
    partial class UpdateSpectacleTitreSize
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ArtistesSpectacle", b =>
                {
                    b.Property<int>("ArtisteId")
                        .HasColumnType("int")
                        .HasColumnName("ArtisteID");

                    b.Property<int>("SpectacleId")
                        .HasColumnType("int")
                        .HasColumnName("SpectacleID");

                    b.HasKey("ArtisteId", "SpectacleId")
                        .HasName("PK__Artistes__23683982BC8F2C45");

                    b.HasIndex("SpectacleId");

                    b.ToTable("ArtistesSpectacles", (string)null);
                });

            modelBuilder.Entity("DAL.Modeles.Artiste", b =>
                {
                    b.Property<int>("ArtisteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ArtisteID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArtisteId"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.HasKey("ArtisteId")
                        .HasName("PK__Artistes__6635EC444C40FE8D");

                    b.ToTable("Artistes");
                });

            modelBuilder.Entity("DAL.Modeles.Billet", b =>
                {
                    b.Property<int>("BilletId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BilletID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BilletId"));

                    b.Property<string>("Civilite")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)");

                    b.Property<decimal>("PrixAchat")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int?>("ProgrammationId")
                        .HasColumnType("int")
                        .HasColumnName("ProgrammationID");

                    b.Property<int?>("TarifId")
                        .HasColumnType("int")
                        .HasColumnName("TarifID");

                    b.HasKey("BilletId")
                        .HasName("PK__Billets__39A625695730C264");

                    b.HasIndex("ProgrammationId");

                    b.HasIndex("TarifId");

                    b.ToTable("Billets");
                });

            modelBuilder.Entity("DAL.Modeles.GroupesSpectacle", b =>
                {
                    b.Property<int>("GroupeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("GroupeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupeId"));

                    b.Property<string>("NomGroupe")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("GroupeId")
                        .HasName("PK__GroupesS__5C811B3043F4298F");

                    b.ToTable("GroupesSpectacles");
                });

            modelBuilder.Entity("DAL.Modeles.GroupesSpectaclesOrganisation", b =>
                {
                    b.Property<int>("GroupeId")
                        .HasColumnType("int")
                        .HasColumnName("GroupeID");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<TimeOnly?>("Duree")
                        .HasColumnType("time");

                    b.Property<string>("TypeSpectacle")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("GroupeId")
                        .HasName("PK__GroupesS__5C811B3044AF5A05");

                    b.ToTable("GroupesSpectaclesOrganisation", (string)null);
                });

            modelBuilder.Entity("DAL.Modeles.Programmation", b =>
                {
                    b.Property<int>("ProgrammationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProgrammationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProgrammationId"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("Heure")
                        .HasColumnType("time");

                    b.Property<string>("Lieu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("SpectacleId")
                        .HasColumnType("int")
                        .HasColumnName("SpectacleID");

                    b.HasKey("ProgrammationId")
                        .HasName("PK__Programm__3AFFDBE06F636068");

                    b.HasIndex("SpectacleId");

                    b.ToTable("Programmation", (string)null);
                });

            modelBuilder.Entity("DAL.Modeles.Spectacle", b =>
                {
                    b.Property<int>("SpectacleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SpectacleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SpectacleId"));

                    b.Property<bool?>("DeconseilleAuxEnfants")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<TimeOnly?>("Duree")
                        .HasColumnType("time");

                    b.Property<string>("Saison")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("SpectacleEnfant1Id")
                        .HasColumnType("int");

                    b.Property<int?>("SpectacleEnfant2Id")
                        .HasColumnType("int");

                    b.Property<int?>("SpectacleEnfant3Id")
                        .HasColumnType("int");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Type")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("SpectacleId")
                        .HasName("PK__Spectacl__55DD5C655BDE6A97");

                    b.HasIndex("SpectacleEnfant1Id");

                    b.HasIndex("SpectacleEnfant2Id");

                    b.HasIndex("SpectacleEnfant3Id");

                    b.ToTable("Spectacles");
                });

            modelBuilder.Entity("DAL.Modeles.TarifsGroupe", b =>
                {
                    b.Property<int>("TarifId")
                        .HasColumnType("int")
                        .HasColumnName("TarifID");

                    b.Property<int>("GroupeId")
                        .HasColumnType("int")
                        .HasColumnName("GroupeID");

                    b.Property<decimal>("Prix")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("TarifId", "GroupeId")
                        .HasName("PK__TarifsGr__425F0DE2907FCD83");

                    b.HasIndex("GroupeId");

                    b.ToTable("TarifsGroupes");
                });

            modelBuilder.Entity("DAL.Modeles.TarifsSpectacle", b =>
                {
                    b.Property<int>("TarifId")
                        .HasColumnType("int")
                        .HasColumnName("TarifID");

                    b.Property<int>("SpectacleId")
                        .HasColumnType("int")
                        .HasColumnName("SpectacleID");

                    b.Property<decimal>("Prix")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("TarifId", "SpectacleId")
                        .HasName("PK__TarifsSp__12CAC99767A5BAE6");

                    b.HasIndex("SpectacleId");

                    b.ToTable("TarifsSpectacles");
                });

            modelBuilder.Entity("DAL.Modeles.TypesTarif", b =>
                {
                    b.Property<int>("TarifId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TarifID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TarifId"));

                    b.Property<string>("NomTarif")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("TarifId")
                        .HasName("PK__TypesTar__57971C5133704716");

                    b.ToTable("TypesTarifs");
                });

            modelBuilder.Entity("SpectaclesGroupe", b =>
                {
                    b.Property<int>("GroupeId")
                        .HasColumnType("int")
                        .HasColumnName("GroupeID");

                    b.Property<int>("SpectacleId")
                        .HasColumnType("int")
                        .HasColumnName("SpectacleID");

                    b.HasKey("GroupeId", "SpectacleId")
                        .HasName("PK__Spectacl__19DCCEF6096A829E");

                    b.HasIndex("SpectacleId");

                    b.ToTable("SpectaclesGroupes", (string)null);
                });

            modelBuilder.Entity("ArtistesSpectacle", b =>
                {
                    b.HasOne("DAL.Modeles.Artiste", null)
                        .WithMany()
                        .HasForeignKey("ArtisteId")
                        .IsRequired()
                        .HasConstraintName("FK__ArtistesS__Artis__412EB0B6");

                    b.HasOne("DAL.Modeles.Spectacle", null)
                        .WithMany()
                        .HasForeignKey("SpectacleId")
                        .IsRequired()
                        .HasConstraintName("FK__ArtistesS__Spect__4222D4EF");
                });

            modelBuilder.Entity("DAL.Modeles.Billet", b =>
                {
                    b.HasOne("DAL.Modeles.Programmation", "Programmation")
                        .WithMany("Billets")
                        .HasForeignKey("ProgrammationId")
                        .HasConstraintName("FK__Billets__Program__48CFD27E");

                    b.HasOne("DAL.Modeles.TypesTarif", "Tarif")
                        .WithMany("Billets")
                        .HasForeignKey("TarifId")
                        .HasConstraintName("FK__Billets__TarifID__47DBAE45");

                    b.Navigation("Programmation");

                    b.Navigation("Tarif");
                });

            modelBuilder.Entity("DAL.Modeles.GroupesSpectaclesOrganisation", b =>
                {
                    b.HasOne("DAL.Modeles.GroupesSpectacle", "Groupe")
                        .WithOne("GroupesSpectaclesOrganisation")
                        .HasForeignKey("DAL.Modeles.GroupesSpectaclesOrganisation", "GroupeId")
                        .IsRequired()
                        .HasConstraintName("FK__GroupesSp__Group__5535A963");

                    b.Navigation("Groupe");
                });

            modelBuilder.Entity("DAL.Modeles.Programmation", b =>
                {
                    b.HasOne("DAL.Modeles.Spectacle", "Spectacle")
                        .WithMany("Programmations")
                        .HasForeignKey("SpectacleId")
                        .HasConstraintName("FK__Programma__Spect__44FF419A");

                    b.Navigation("Spectacle");
                });

            modelBuilder.Entity("DAL.Modeles.Spectacle", b =>
                {
                    b.HasOne("DAL.Modeles.Spectacle", "SpectacleEnfant1")
                        .WithMany("SpectaclesParent1")
                        .HasForeignKey("SpectacleEnfant1Id")
                        .HasConstraintName("FK_Spectacle_SpectacleEnfant1");

                    b.HasOne("DAL.Modeles.Spectacle", "SpectacleEnfant2")
                        .WithMany("SpectaclesParent2")
                        .HasForeignKey("SpectacleEnfant2Id")
                        .HasConstraintName("FK_Spectacle_SpectacleEnfant2");

                    b.HasOne("DAL.Modeles.Spectacle", "SpectacleEnfant3")
                        .WithMany("SpectaclesParent3")
                        .HasForeignKey("SpectacleEnfant3Id")
                        .HasConstraintName("FK_Spectacle_SpectacleEnfant3");

                    b.Navigation("SpectacleEnfant1");

                    b.Navigation("SpectacleEnfant2");

                    b.Navigation("SpectacleEnfant3");
                });

            modelBuilder.Entity("DAL.Modeles.TarifsGroupe", b =>
                {
                    b.HasOne("DAL.Modeles.GroupesSpectacle", "Groupe")
                        .WithMany("TarifsGroupes")
                        .HasForeignKey("GroupeId")
                        .IsRequired()
                        .HasConstraintName("FK__TarifsGro__Group__52593CB8");

                    b.HasOne("DAL.Modeles.TypesTarif", "Tarif")
                        .WithMany("TarifsGroupes")
                        .HasForeignKey("TarifId")
                        .IsRequired()
                        .HasConstraintName("FK__TarifsGro__Tarif__5165187F");

                    b.Navigation("Groupe");

                    b.Navigation("Tarif");
                });

            modelBuilder.Entity("DAL.Modeles.TarifsSpectacle", b =>
                {
                    b.HasOne("DAL.Modeles.Spectacle", "Spectacle")
                        .WithMany("TarifsSpectacles")
                        .HasForeignKey("SpectacleId")
                        .IsRequired()
                        .HasConstraintName("FK__TarifsSpe__Spect__3E52440B");

                    b.HasOne("DAL.Modeles.TypesTarif", "Tarif")
                        .WithMany("TarifsSpectacles")
                        .HasForeignKey("TarifId")
                        .IsRequired()
                        .HasConstraintName("FK__TarifsSpe__Tarif__3D5E1FD2");

                    b.Navigation("Spectacle");

                    b.Navigation("Tarif");
                });

            modelBuilder.Entity("SpectaclesGroupe", b =>
                {
                    b.HasOne("DAL.Modeles.GroupesSpectacle", null)
                        .WithMany()
                        .HasForeignKey("GroupeId")
                        .IsRequired()
                        .HasConstraintName("FK__Spectacle__Group__4D94879B");

                    b.HasOne("DAL.Modeles.Spectacle", null)
                        .WithMany()
                        .HasForeignKey("SpectacleId")
                        .IsRequired()
                        .HasConstraintName("FK__Spectacle__Spect__4E88ABD4");
                });

            modelBuilder.Entity("DAL.Modeles.GroupesSpectacle", b =>
                {
                    b.Navigation("GroupesSpectaclesOrganisation");

                    b.Navigation("TarifsGroupes");
                });

            modelBuilder.Entity("DAL.Modeles.Programmation", b =>
                {
                    b.Navigation("Billets");
                });

            modelBuilder.Entity("DAL.Modeles.Spectacle", b =>
                {
                    b.Navigation("Programmations");

                    b.Navigation("SpectaclesParent1");

                    b.Navigation("SpectaclesParent2");

                    b.Navigation("SpectaclesParent3");

                    b.Navigation("TarifsSpectacles");
                });

            modelBuilder.Entity("DAL.Modeles.TypesTarif", b =>
                {
                    b.Navigation("Billets");

                    b.Navigation("TarifsGroupes");

                    b.Navigation("TarifsSpectacles");
                });
#pragma warning restore 612, 618
        }
    }
}
